version: '3.4'

services:
  pgdb:
    restart: "no"
    container_name: "aiodal_pgdb"
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c 'max_connections=100'
    expose:
      - "5432"
    ports:
      - "5454:5432" # for debugging 
    shm_size: 1g

  # An example of a simple local test setup with postgres... called via Makefile
  testapp:
    restart: "no"
    image: aiodal:dev
    container_name: "aiodal_testapp"
    build: .
    volumes:
      - .:/app
    command:
      - /bin/sh
      - -c
      - |
        PGPASSWORD=${POSTGRES_PASSWORD} dropdb -h pgdb -p 5432 -U ${POSTGRES_USER} -e -f --if-exists testdb && \
        PGPASSWORD=${POSTGRES_PASSWORD} createdb -h pgdb -p 5432 -U ${POSTGRES_USER} -e testdb
        poetry run alembic upgrade head
        coverage run --source=aiodal/ -m pytest -s -v && coverage report -m --fail-under=90
        poetry run mypy aiodal --strict
        PGPASSWORD=${POSTGRES_PASSWORD} dropdb -h pgdb -p 5432 -U ${POSTGRES_USER} -e -f --if-exists testdb
    depends_on:
      - pgdb

volumes:
  pgdata:


