name: unittests

on:
  pull_request:
    branches:
      - development*

  push:
    branches:
      - development*

jobs:
  container-job:
    runs-on: ubuntu-latest

    container: bsnacks000/python-poetry:3.11-1.3.2

    services:
      pgdb:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: pgdb
      POSTGRES_PORT: 5432
      ENVIRONMENT: testing
      AUTH0_TESTING_CLIENT_SECRET: ${{ secrets.AUTH0_TESTING_CLIENT_SECRET }}
      AUTH0_TESTING_CLIENT_ID: ${{ secrets.AUTH0_TESTING_CLIENT_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: poetry install

      - name: Run migrations
        run: poetry run alembic upgrade head

      - name: Run tests
        run: coverage run --source=aiodal/ -m pytest -s -v -m "not e2e" && coverage report -m --fail-under=90

      - name: Run e2e tests 
        run: coverage run --source=aiodal/ -m pytest -s -v -m "e2e"

      - name: Run mypy
        run: poetry run mypy aiodal --strict
