name: unittests

on:
  pull_request:
    branches:
      - development*

  push:
    branches:
      - development*

jobs:
  container-job:
    runs-on: ubuntu-latest

    container: bsnacks000/python-poetry:3.11-1.3.2

    services:
      tsdb:
        image: timescale/timescaledb:2.5.1-pg13
        env:
          POSTGRES_USER: bsnacks000
          POSTGRES_PASSWORD: iamgroot666
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    env:
      POSTGRES_USER: bsnacks000
      POSTGRES_PASSWORD: iamgroot666
      POSTGRES_HOST: tsdb
      POSTGRES_PORT: 5432 # default
      ENVIRONMENT: testing

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: poetry install

      - name: Run migrations
        run: poetry run alembic upgrade head

      - name: Run tests
        run: poetry run pytest -v --cov=aiodal/ --cov-report=term-missing

      - name: Run mypy
        run: poetry run mypy aiodal --strict
